# Generated by Django 3.2.7 on 2022-02-13 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='extra',
            field=models.TextField(blank=True),
        ),
    ]
