# Generated by Django 4.0.3 on 2022-03-25 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('address_first', models.CharField(max_length=255)),
                ('address_second', models.CharField(blank=True, max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('number_first', models.CharField(blank=True, max_length=255)),
                ('number_second', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Feathers_to_our_cap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Welfare_measures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('details', models.TextField()),
            ],
        ),
    ]
